### ISSUE TITLE
Trying to keep text vertically centered in version 1.0.3

### ISSUE THREAD

**Issue by BerndN** [stam66/tristate#1]
Stam,

I tried my best to keep text vertically centered for v. 1.0.3

Here is the changed handler "formatFieldText"

[formatFieldText-KeepTxtVerticallyCentered.txt](https://github.com/stam66/tristate/files/12394237/formatFieldText-KeepTxtVerticallyCentered.txt)

Kind regards
Bernd

**Comment by BerndN** [comment]
I think it performs slightly better

**Comment by stam66** [comment]
it certainly performs well - I've not really digested the algorithm but placing it as is into the script works fine -- thank you.
