### ISSUE TITLE
Non-persistent properties

### ISSUE THREAD

**Issue by stam66** [stam66/tristate#2]
Upon saving a stack with a widget whose properties have been modified, closing and re-opening the stack fails to restore the previous set switchValue and it defaults to 'Center'.

**Comment by BerndN** [comment]
> Some properties are not saved - the switchValue defaults to 'Center'

In handler "createVisualControls" make the switchValue a conditional as indicated by code between comments
Please initialise tSwitchValue

```
   set the innerGlow of control id sIndicatorID to tInnerGlow -- current code
   
   ## make switchValue persistent
   put the switchValue of me into tSwitchValue
   if tSwitchValue is empty then
      set the switchValue of me to "Center"
   else
      set the switchValue of me to tSwitchValue
   end if
   ## end make switchValue persistent
   
   if the width of me is empty or the width of me is 0 then -- current code

```


So it seems that the widget stores the custom properties on save and restores them when loading

**Comment by stam66** [comment]
This is the same with colours, default text and min/max text size settings; this is code that was taken from the lesson on script widgets; and while **_all_** other properties are saved (such as backgroundColor), the switchValue is not.  

A quick trawl through the script did not really reveal what the issue might be, but I'll have to spend more time with this I guess. 

Since it's the _only_ setting not saved, it must be something in the code... but for now I'm stumped!

**Comment by BerndN** [comment]
> Since it's the only setting not saved, it must be something in the code... but for now I'm stumped!

I think it is because in your code you override the custom property:

`set the switchValue of me to "center"`

If you instead code:

`set the switchValue of me to the switchValue of me`

then the getProp handler returns either the stored value of "Center"

```
getProp switchValue
	local tValue
	put the switchValue of me into tValue
	if tValue is empty then put "Center" into tValue
	return tValue
end switchValue
```
So please forget my clumsy proposition from above and try 

`set the switchValue of me to the switchValue of me`


It works for me in restoring the switchValue of saved widgets. getProp switchValue takes care of it.

**Comment by stam66** [comment]
Dear Bernd thank you once again - I only quickly read you previous response while at work and didn't quite understand your solution. 

Searching for and finding _set the switchValue of me to "center"_ in the initialisation handler was a DOH! moment and yes you are entirely correct, changing that to _set the switchValue of me to the switchValue of me_ fixed the issue. 

Great spot, thank you.
