### ISSUE TITLE
Slow initialisation

### ISSUE THREAD

**Issue by stam66** [stam66/tristate#3]
Creating a widget has a small degree of lag.
Saving a stack with this widget on a card, closing and reopening it causes more noticeable lag, with the widget become visible 1-2 seconds after the the card has opened.

The effect is greatly compounded with multiple widgets; putting 3 such widgets on a card leads to a delay of 4-5 seconds until the widgets are visible (M2 Pro Mac).

**Comment by BerndN** [comment]
I think I found the culprit for glacial speed when opening (glaciers move faster nowadays though)

It is the animated move of the indicatorGraphic (in 200 milliseconds)

I introduced an new script local variable and added it to the others
local sIsOpening

change handler openControl to indicate it is  opening using the script local sIsOpening

```
on openControl
   put true into sIsOpening -- 
   createVisualControls
   layoutVisualControls
   updateVisualControls
   put false into sIsOpening --
end openControl
```
in handler updateIndicatorForValue change the switch statement
with the condition based on sIsOpening

   ```
 switch the switchValue of me
      case "Left"
         set the backgroundColor of control id sBackroundID to the leftColor of me
         put the left of control id sBackroundID + 3 + the width of control id sIndicatorID / 2 into tX
         if sIsOpening then
            set the loc of control id sIndicatorID to tx, item 2 of the loc of control id sBackroundID
         else
            move control id sIndicatorID to tX, item 2 of the loc of control id sBackroundID in 200 milliseconds
         end if
         set the left of control id sIndicatorID to the left of control id sBackroundID + 2
         break
      case "Center"
         set the backgroundColor of control id sBackroundID to the centerColor of me
         if sIsOpening then
            set the loc of control id sIndicatorID to the loc of control id sBackroundID
         else
            move control id sIndicatorID to the loc of control id sBackroundID in 200 milliseconds
         end if
         break
      case "Right"
         set the backgroundColor of control id sBackroundID to the rightColor of me
         put the right of control id sBackroundID - 3 - the width of control id sIndicatorID / 2 into tX
         if sIsOpening then
            set the loc of control id sIndicatorID to tx, item 2 of the loc of control id sBackroundID
         else
            move control id sIndicatorID to tX, item 2 of the loc of control id sBackroundID in 200 milliseconds
         end if
         set the right of control id sIndicatorID to the right of control id sBackroundID - 2
         break
   end switch
```
With these changes the widget ( tested with 5 on card 1) starts instantly and opening a card also has no more delays

**Comment by stam66** [comment]
That's weird because I tried to do the something similar...

I followed Ali's suggestion and bypassed the handler `if there is a control 1 of me` but seemed to do nothing...
Thanks for your solution, I'll delve into it when I'm back from work...

**Comment by stam66** [comment]
I've also found the equivalent of [code][/code] tags on here are three backticks before and after the code : ``` 

I hope you don't mind, I added these to your post for readability

**Comment by BerndN** [comment]
The code looks good, I did not know one could format it.

As far as Ali's suggestion is concerned:
What it does it prevents openControl to be sent when going to a card with initialized widgets. When you go through cards repeatedly widgets would be initialised on every visit, not just the first visit
And I kind of like the idea to avoid unnecessary processing.

However in your case it is the first time that a widget is opened that makes the widget slow because of the 
move in 200 milliseconds.
That slowdown is avoided by adding the conditionals for first time/initialization
```
if sIsOpening then
   -- no move, just set loc
   set the loc of control id sIndicatorID to tx, item 2 of the loc of control id sBackroundID
else
   -- with move
   move control id sIndicatorID to tX, item 2 of the loc of control id sBackroundID in 200 milliseconds
end if
```


The addition of Ali's code would look like this

```
on openControl
   if there is a control 1 of me then
    exit openControl
   end if
   put true into sIsOpening
   createVisualControls
   layoutVisualControls
   updateVisualControls
   put false into sIsOpening
end openControl
```

I guess that instead of **exit openControl** you could also code **pass openControl**

I tested with **exit openControl** and it works fine.
Although since it now very fast I could not see a difference.

Of course the script local variable sIsOpening could be named better, maybe sInitializing or somesuch

**Comment by stam66** [comment]
yeh formatting is not bad - also instead of three back ticks, if you surround code with a single back tick each side it becomes inline formatted, for example `put true into sIsOpening` was the bit I was missing ;)

I've modified the code with your suggestion (and thank you once again!) and seems to work just fine, which means that's the last outstanding issue I could think of 👍
