### ISSUE TITLE
Change of top line of script to better identify the widget

### ISSUE THREAD

**Issue by BerndN** [stam66/tristate#4]
I suggest to change the top line of your script from

**script "com.sk.tristate.livecodescript"**

to

**script "com.sk.widget.tristate"**

This seems to be in line with other script widgets and it shows up better in "tinyDict" and dictionary.

**Comment by stam66** [comment]
Changed (in external editor as not possible within LC). As there are a few changes I'll put this down as minor point release to keep track - thank you Bernd!
