### ISSUE TITLE
tristate should have regular dictionary entries

### ISSUE THREAD

**Issue by BerndN** [stam66/tristate#5]
I added inline comments to make individual entries for the properties for dictionaries

[script for 1.0.41 with added dictionary comments.txt](https://github.com/stam66/tristate/files/12427950/script.for.1.0.41.with.added.dictionary.comments.txt)

This includes the change of the top line.

Otherwise it is the the code of version 1.0.41

**Comment by stam66** [comment]
Amazing, thank you Bernd!
