### ISSUE TITLE
triStateChanged message is somehow lost

### ISSUE THREAD

**Issue by BerndN** [stam66/tristate#6]
'triStateChanged' does not trigger and I do not see any code relating to it.

**Comment by stam66** [comment]
Hi Bernd, I took your code that you had kindly sent with the proper property declarations for the Dictionary, but it seems that for some reason that was missing the last line in updateIndicatorForValue that emitted the triStateChanged message and I hadn't noticed, so had just rebuilt the widget based on that.

I've updated the source code and the packaged widget, hopefully this is now sorted.
On that note, I've simplified the code slightly by removing the variable pValue and just referring directly to _the switchValue of me_ and the handler is renamed to _updateIndicator_. 

I think it's resolved - I tested on card script:
```
on triStateChanged pValue, pID
    answer "Widget id" && pID && "now has the state:" && pValue
end triStateChanged
```
and works as expected :)

As far as I can see the only remaining issue is the slow initialisation (FWIW my LC10 was already running native ARM and not in Rosetta testing on Win is still pending)


Thank you as always for your tireless attention to detail!!!🥇
Stam
