### ISSUE TITLE
Version 1.0.43 does not seem to emit "triStateChanged"

### ISSUE THREAD

**Issue by BerndN** [stam66/tristate#7]
```dispatch "triStateChanged" to me with the switchValue of me, the id of me```

This is the current version of triStateChange in 1.0.43

Does that work for you?

I have tried but the message does not seem to be emitted. Neither on the card script level nor at the widget script level.

I had tried that version before but it did not work for me then either. That was the reason I dispatched it to the owner of me as in the now out commented version in the Diff does

```dispatch "triStateChanged" to the owner of me with the switchValue of me, the id of me```

That worked on a the card level.

**Comment by BerndN** [comment]
If you also find that triStateChanged message is not sent please consider that in its current state it would also fire on initialisation. That may or may not be wanted.
If not wanted I suggest that you set in handler "openControl" at the end of the handler  "sIsOpening" to false.
Then you can wrap triStateChanged in handler "updateIndicator" in a conditional.

```
if not sIsOpening then
   dispatch "triStateChanged" to the owner of me with the switchValue of me, the id of me
end if
```

This would avoid the message to be emitted when opening a stack with triState widget.

Here is a dictionary entry for triStateChanged

```
/**
Type: Message
Summary: <triStateChanged> is sent to the owner of the widget when user changes state

Syntax: triStateChanged { left | center | right }, { the id of the sender }
Example:on triStateChanged pWhichWay, pSenderID
  put pWichWayy && pSenderId
end triStateChanged

Parameters:
Param1: text: left|center|right
Param2: ID: the short id of sender
Description: use <triStateChanged> message to react to user action on widget.
Put the handler one level higher than the widget:
If widget is placed on a card use card script to trap the <triStateChanged> message
*/
on triStateChanged -- fake handler for dictionary
end triStateChanged -- fake handler for dictionary

private command updateIndicator -- current code
```

Oddly enough I had to add the fake handler on triStateChanged at the end of the dictionary entry for the dictionary creation to pick up the triStateChanded as Message. As far as I can see it does no harm.
Of course this assumes that you adopt the message to be sent to the owner of the widget.

**Comment by stam66** [comment]
Bernd, I know I've said it many times, but once again thank you. 
Not only have you helped make this a _much_ better widget but you're upping my coding game at the same time :-)

I'll update to include the code above.

PS: No the 'send to me' didn't work, I meant to roll it back (it is now)

**Comment by stam66** [comment]
On further issue with triStateChanged is that it fires even if indicator hasn't changed position (i.e. if the user clicks on the indicator but doesn't move it) which I don't think is correct as the state hasn't changed.

I've added a new script local variable `sPreviousValue` which stores the switchValue on mouseDown and is reset on mouseUp/mouseRelease, and added a check before emitting triStateChanged: 
```
if not sIsOpening and sPreviousValue <> the switchValue of me then 
      dispatch "triStateChanged" to the owner of me with the switchValue of me, the id of me
end if
```

This seems to work fine - I'll roll these changes up into next version and post.
Many thanks once again!

**Comment by BerndN** [comment]
Stam,

I noticed that the message triStateChanged does not show up in the dictionaries.

The reason is a missing slash before the two asterisks in the opening block comment for triStateChanged

it should be:
```
/**
```
then it works

I think it is pretty much ready then.

I learned a lot from your script widget which I find a useful widget for special cases.
And I understood Ali's motivation better to develop script widgets. The uptake might be better than for LCB widgets.
But it is in no way trivial to do a script widget right.
I thank you for your patience and persistence. It was fun to delve into the code.

**Comment by stam66** [comment]
Hi Bernd, already spotted and updated ;)

**Comment by stam66** [comment]
> The uptake might be better than for LCB widgets.
But it is in no way trivial to do a script widget right.

Agree completely. I just wish there was more  reference material for LCB, more examples online as currently it's an exercise in frustration trying to get into it... (there are examples, but because the basics aren't covered adequately, trying to apply to different use-cases just draws blanks...)

The script widgets are a nice addition and just want to see a bit more polish in the IDE support for these...

Once again **thank you** for your invaluable help with this widget - it would probably have taken me a _whole_ lot longer to work around the issues (assuming I'd have been able to in the first place!).
